name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout git

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build --platform linux/amd64 --build-arg NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} --tag ${{ secrets.DOCKER_USERNAME }}/thanksgiving-web:latest .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/thanksgiving-web:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from DockerHub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/thanksgiving-web:latest
      - name: Delete old Docker container
        run: docker rm -f thanksgiving-web-container || true
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name thanksgiving-web-container -e MONGODB_URI="${{ secrets.MONGODB_URI }}" -e NEXT_PUBLIC_BASE_URL="${{ secrets.NEXT_PUBLIC_BASE_URL }}" ${{ secrets.DOCKER_USERNAME }}/thanksgiving-web:latest
      - name: Clean up old Docker images
        if: always()
        run: docker image prune -af